# Generated by Django 5.2.3 on 2025-06-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originCountry', models.CharField(max_length=64)),
                ('destinationCountry', models.CharField(max_length=64)),
                ('numberOfnights', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
