# Generated by Django 5.2.3 on 2025-06-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiatouragency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='numberOfnights',
            new_name='numberOfNights',
        ),
    ]
